language: ruby
rvm:
  - 2.7.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  chrome: stable
services:
  - postgresql
bundler_args: --jobs=3 --retry=3 --without development
before_script:
  - psql -c 'create database cfp_app_test;' -U postgres
